<?php
require __DIR__.'/../app/bootstrap.php';require_admin();
$id=filter_input(INPUT_GET,'id',FILTER_VALIDATE_INT);$test=null;
if($id){$s=$pdo->prepare("SELECT * FROM tests WHERE id=?");$s->execute([$id]);$test=$s->fetch();if(!$test)exit('Toets niet gevonden.');}
$subjects=$pdo->query("SELECT id,name FROM subjects ORDER BY name")->fetchAll();
$topics=$pdo->query("SELECT id,subject_id,name FROM topics ORDER BY subject_id,name")->fetchAll();
if($_SERVER['REQUEST_METHOD']==='POST'){
 $title=trim($_POST['title']??'');$description=trim($_POST['description']??'');$topicId=filter_input(INPUT_POST,'topic_id',FILTER_VALIDATE_INT);$testType=$_POST['test_type']??'mixed';$active=isset($_POST['is_active'])?1:0;
 if(!in_array($testType,['vocabulary','multiple_choice','mixed'],true))$testType='mixed';
 if($title==='')$error='Een titel is verplicht.';
 elseif(!$topicId)$error='Kies een onderwerp.';
 elseif(in_array($testType,['multiple_choice','vocabulary'],true) && $id){
     $requiredType=$testType==='multiple_choice'?'multiple_choice':'open';
     $wrongLabel=$testType==='multiple_choice'?'open':'meerkeuze';
     $x=$pdo->prepare("SELECT COUNT(*) FROM questions WHERE test_id=? AND question_type<>?");
     $x->execute([$id,$requiredType]);
     if((int)$x->fetchColumn()>0)$error='Deze toets bevat vragen van het verkeerde type. Een toets van dit type mag alleen '.$wrongLabel.'vragen bevatten.';
 }
 elseif($id){$s=$pdo->prepare("UPDATE tests SET topic_id=?,title=?,description=?,test_type=?,is_active=? WHERE id=?");$s->execute([$topicId,$title,$description,$testType,$active,$id]);redirect('questions.php?test_id='.$id);}
 else{$s=$pdo->prepare("INSERT INTO tests(topic_id,title,description,test_type,is_active) VALUES(?,?,?,?,?)");$s->execute([$topicId,$title,$description,$testType,$active]);redirect('questions.php?test_id='.$pdo->lastInsertId());}
}
?><!doctype html><html lang="nl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Toets</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"></head><body class="bg-light"><main class="container py-4" style="max-width:760px"><a href="admin.php">&larr; Beheer</a><div class="card shadow-sm mt-3"><div class="card-body p-4"><h1 class="h3"><?= $id?'Toets bewerken':'Nieuwe toets'?></h1><?php if(!empty($error)):?><div class="alert alert-danger"><?=e($error)?></div><?php endif;?><form method="post"><label class="form-label">Titel</label><input class="form-control mb-3" name="title" value="<?=e($test['title']??'')?>" required><label class="form-label">Beschrijving</label><textarea class="form-control mb-3" name="description" rows="3"><?=e($test['description']??'')?></textarea><label class="form-label">Type toets</label><select class="form-select mb-3" name="test_type"><option value="vocabulary" <?=($test['test_type']??'mixed')==='vocabulary'?'selected':''?>>Woordjes oefenen</option><option value="multiple_choice" <?=($test['test_type']??'mixed')==='multiple_choice'?'selected':''?>>Alleen multiple choice</option><option value="mixed" <?=($test['test_type']??'mixed')==='mixed'?'selected':''?>>Combinatie van multiple choice en open vragen</option></select><div class="form-text mb-3">Bij Woordjes oefenen gebruik je bij voorkeur open vragen met één of meer goede vertalingen.</div><label class="form-label">Onderwerp</label><select class="form-select mb-3" name="topic_id" required><option value="">Kies een onderwerp...</option><?php foreach($topics as $topic):?><option value="<?=$topic['id']?>" <?=isset($test['topic_id'])&&(int)$test['topic_id']===(int)$topic['id']?'selected':''?>><?php $subjectName='';foreach($subjects as $subject)if((int)$subject['id']===(int)$topic['subject_id']){$subjectName=$subject['name'];break;}?><?=e($subjectName.' — '.$topic['name'])?></option><?php endforeach;?></select><div class="form-check mb-3"><input class="form-check-input" type="checkbox" name="is_active" id="active" <?=!isset($test['is_active'])||$test['is_active']?'checked':''?>><label class="form-check-label" for="active">Actief</label></div><button class="btn btn-primary">Opslaan</button></form></div></div></main></body></html>